<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>alumno.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="alumno.ico" />
  </ItemGroup>

</Project>